### ISSUE TITLE
Builds on 9.14.1 got broken since the 1.1.0 release

### ISSUE THREAD

**Issue by nikita-volkov** [kazu-yamamoto/crypton#68]
Here's the output:

```

[ 8 of 14] Compiling Data.X509.PublicKey ( Data/X509/PublicKey.hs, dist/build/Data/X509/PublicKey.o, dist/build/Data/X509/PublicKey.dyn_o )
Data/X509/PublicKey.hs:255:68: error: [GHC-39999]
    • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                         X25519.PublicKey’
        arising from a use of ‘convert’
    • In the first argument of ‘toBitArray’, namely ‘(convert pubkey)’
      In the second argument of ‘($)’, namely
        ‘toBitArray (convert pubkey) 0’
      In the expression: BitString $ toBitArray (convert pubkey) 0
    |
255 |         asn1Container Sequence [pkalg] ++ [BitString $ toBitArray (convert pubkey) 0]
    |                                                                    ^^^^^^^

Data/X509/PublicKey.hs:257:68: error: [GHC-39999]
    • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                         X448.PublicKey’
        arising from a use of ‘convert’
    • In the first argument of ‘toBitArray’, namely ‘(convert pubkey)’
      In the second argument of ‘($)’, namely
        ‘toBitArray (convert pubkey) 0’
      In the expression: BitString $ toBitArray (convert pubkey) 0
    |
257 |         asn1Container Sequence [pkalg] ++ [BitString $ toBitArray (convert pubkey) 0]
    |                                                                    ^^^^^^^

Data/X509/PublicKey.hs:259:68: error: [GHC-39999]
    • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                         Ed25519.PublicKey’
        arising from a use of ‘convert’
    • In the first argument of ‘toBitArray’, namely ‘(convert pubkey)’
      In the second argument of ‘($)’, namely
        ‘toBitArray (convert pubkey) 0’
      In the expression: BitString $ toBitArray (convert pubkey) 0
    |
259 |         asn1Container Sequence [pkalg] ++ [BitString $ toBitArray (convert pubkey) 0]
    |                                                                    ^^^^^^^

Data/X509/PublicKey.hs:261:68: error: [GHC-39999]
    • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                         Ed448.PublicKey’
        arising from a use of ‘convert’
    • In the first argument of ‘toBitArray’, namely ‘(convert pubkey)’
      In the second argument of ‘($)’, namely
        ‘toBitArray (convert pubkey) 0’
      In the expression: BitString $ toBitArray (convert pubkey) 0
    |
261 |         asn1Container Sequence [pkalg] ++ [BitString $ toBitArray (convert pubkey) 0]
    |                                                                    ^^^^^^^

[12 of 14] Compiling Data.X509.Signed ( Data/X509/Signed.hs, dist/build/Data/X509/Signed.o, dist/build/Data/X509/Signed.dyn_o )
```

**Comment by kazu-yamamoto** [comment]
Due to the hackage server problem, uploading crypton-x509* was delayed.
But now uploaded.

**Comment by kazu-yamamoto** [comment]
I modified metadata of crypton-x509 v1.7* and v1.8.0 to use `crypton` < 1.1.

**Comment by identicalsnonwflake2** [comment]
I'm seeing a similar error, `No instance for ‘Mem.ByteArrayAccess
                         (crypton-1.1.1:Crypto.Hash.Types.Digest SHA256)’`

**Comment by kazu-yamamoto** [comment]
Please migrate your project from `memory` to `ram`.

**Comment by identicalsnonwflake2** [comment]
Thanks, that worked!

**Comment by kazu-yamamoto** [comment]
Fixed, and crypton 2.0.0 is released.

The cause was `memory`: the `ByteArrayAccess` instances your build could not
find were in a package that had stopped moving with GHC. crypton depends on
`ram` now -- `ram >=0.20.1 && <0.23` -- which is where the fix you needed
lives, and that is also the answer @identicalsnonwflake2 was given above.

9.14.1 is in `tested-with` and in CI, alongside 9.2.8, 9.4.8, 9.6.7, 9.8.4,
9.10.2 and 9.12.4, so the eighteen-job matrix builds this on every change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
